#!/bin/bash
#title          :webp2gif
#description    :convert animated webp to gif
#author         :elsonwx
#date           :20200205
#usage          :webp2gif input.webp [output.gif]
#==============================================================================
version=0.3
if [[ $1 == "-v" || $1 == "--version" ]];then
    echo "version:$version"
    exit 0
fi
if [[ $1 == "-h" || $1 == "--help" || -z $1 ]];then
    cat <<EOM

$(basename $0) version:$version

Usage: $(basename $0) [-v|-h] <input.webp> [output.gif]

Options:
  -v, --version  Display the version of the script
  -h, --help     Display a brief usage message

Notes: The output file name is optional.
       If not supplied the gif extension will be used with the input filename,
       e.g. foobar.webp --> foobar.gif
       
EOM
    exit 0
fi
cur_dir=$(pwd)
temp_dir=$(mktemp -d)
cd $temp_dir
webpfile=$1
if [[ -z $2 ]];then
    giffile=${webpfile%%.webp}.gif
else
    giffile=$2
fi
if [[ ! -f $webpfile ]];then
    webpfile="$cur_dir/$webpfile"
    if [[ ! -f $webpfile ]];then
        echo "input file not found -- \"$webpfile\""
        exit 1
    fi    
fi

# abend on any processing errors so that we:
#  - don't see a success message when there is a failure
#  - set the exit code to non-zero
set -e

webpfileinfo="$(webpmux -info "$webpfile")"
frames_num=$(echo "$webpfileinfo"|sed -n 's/Number of frames: //p')
table_line=$(echo "$webpfileinfo"|grep -nh  "No.: width.*"|cut -d : -f 1)
duration=0
echo "Extracting webp frames..."
for i in $(seq -f "%03g" 1 $frames_num);do
    webpmux -get frame $i "$webpfile" -o "$i.webp"
    
    width=$(echo "$webpfileinfo"|awk -v cur_line="$((table_line+10#$i))" '{if(NR==cur_line) print $2}')
    echo $width
    offset_x=$(echo "$webpfileinfo"|awk -v cur_line="$((table_line+10#$i))" '{if(NR==cur_line) print $5}')
    duration=$(echo "$webpfileinfo"|awk -v cur_line="$((table_line+10#$i))" '{if(NR==cur_line) print $7}')
    new_width=$((width+offset_x))
    height=$(echo "$webpfileinfo"|awk -v cur_line="$((table_line+10#$i))" '{if(NR==cur_line) print $3}')
    offset_y=$(echo "$webpfileinfo"|awk -v cur_line="$((table_line+10#$i))" '{if(NR==cur_line) print $6}')
    new_height=$((height+offset_y))
    dwebp "$i.webp" -o "$i.png"
    convert -gravity southeast -extent ${new_width}x${new_height} -background none "$i.png" "$i.png"
done
echo "converting all png frame file to gif..."
duration=$((duration/10))
convert -delay $duration -loop 0 *.png animation.gif
mv $temp_dir/animation.gif "$cur_dir/$giffile"
rm -rf $temp_dir
echo "finished with success!"
